
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.cluster.warehouse: INFO

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/?minPoolSize=50&maxPoolSize=10000&shellBatchSize=500
      database: warehouse
  thymeleaf:
    cache: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# Application specific properties for production
# ===================================================================

application:
  batch:
    upload:
      dir: ./logs/prod
      batchSize: 10000
      delimiter: ;
