# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
      name: warehouse
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 11MB
server:
    servlet:
        session:
            cookie:
                http-only: true

# ===================================================================
# Application specific properties for all profiles
# ===================================================================

