version: '2'
services:
  cluster-app:
    image: warehouse
    environment:
    - _JAVA_OPTIONS=-Xmx512m -Xms256m
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_DATA_MONGODB_URI=mongodb://warehouse-mongodb:27017
    - SPRING_DATA_MONGODB_DATABASE=cluster
    - APP_SLEEP=10 # gives time for the database to boot before the application
    ports:
    - 8080:8080
  cluster-mongodb:
    extends:
      file: mongodb.yml
      service: warehouse-mongodb
